# Autogenerated by Sencha, Inc. on: 14-Sep-2016 01:33:33
FROM openjdk:8-jre-alpine

RUN apk update && apk upgrade && apk --update add \
    ruby build-base libstdc++ tzdata bash ttf-dejavu freetype fontconfig wget curl

RUN wget http://cdn.sencha.com/cmd/6.2.0.103/no-jre/SenchaCmd-6.2.0.103-linux-amd64.sh.zip -O senchacmd.zip && unzip senchacmd.zip && rm senchacmd.zip && chmod +x SenchaCmd-6.2.0.103-linux-amd64.sh
RUN ./SenchaCmd-6.2.0.103-linux-amd64.sh -q -dir /opt/Sencha/Cmd/6.2.0.103 -Dall=true
RUN rm SenchaCmd-6.2.0.103-linux-amd64.sh && chmod +x /opt/Sencha/Cmd/6.2.0.103/sencha

ENV PJS_HOME=/usr/lib/phantomjs
RUN cd /tmp && \
  curl -Ls "https://github.com/israelroldan/docker-sencha-cmd/raw/phantomjs-2.1.1/dockerized-phantomjs-2.1.1.tar.gz" | tar xz -C / && \
  ln -s "$PJS_HOME/bin/phantomjs" /usr/bin/phantomjs && \
  rm /opt/Sencha/Cmd/6.2.0.103/bin/linux-x64/phantomjs/phantomjs && \
  ln -s "$PJS_HOME/bin/phantomjs" /opt/Sencha/Cmd/6.2.0.103/bin/linux-x64/phantomjs/phantomjs

ENTRYPOINT ["/opt/Sencha/Cmd/6.2.0.103/sencha"]

WORKDIR /code